source 'https://gitlab.ysjzb.net/mobile/iOS/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "10.0"
use_frameworks! :linkage => :static

target 'TokenCoreCapo_Example' do
  pod 'TokenCoreCapo', :path => '../'

end
